### ISSUE TITLE
图和表同正文的间距是不是过大？

### ISSUE THREAD

**Issue by ipez** [BHOSC/BUAAthesis#187] opened 2016-12-12 03:18 UTC
尝试修改cls文件里的这几个参数设置，发现变化不大，求解。

\setlength{\floatsep}{3pt plus 3pt minus 2pt}      % 图形之间或图形与正文之间的距离
\setlength{\abovecaptionskip}{10pt plus 1pt minus 1pt} % 图形中的图与标题之间的距离
\setlength{\belowcaptionskip}{3pt plus 1pt minus 2pt} % 表格中的表与标题之间的距离

另外，三线表格上下线应为粗实线，查了一下需要package{booktabs}，建议添加。

**Comment by sighingnow** [comment] 2016-12-12 17:04
> 另外，三线表格上下线应为粗实线，查了一下需要package{booktabs}，建议添加。

I have fixed this in #188 and add documentation for how to use it. Thanks very much for your suggestions.

> 图和表同正文的间距是不是过大？

Adjusting the value of `\intextsep` will affect the margin between figures or tables between common text. For example:

~~~tex
\setlength{\intextsep}{2.0pt plus 1.0pt minus 1.0pt}
~~~

Place the above code in your preamble and your will find some clear differences. Some discussion here may be helpful: http://tex.stackexchange.com/questions/26521/how-to-change-the-spacing-between-figures-tables-and-text . However, concerning there is no specific standard in our thesis manual, I don't think we should include this setting in the cls file. It should be left as personal preference and I will add some description later about how to set the margin in our documentation.

Feel free to comment here if your have any further question about this issue. And @huxuan, any suggestions ?

**Comment by huxuan** [comment] 2016-12-13 01:51
@sighingnow Looks good to me. I prefer to leave this setting as user specified.

**Comment by ipez** [comment] 2016-12-15 04:49
@sighingnow @huxuan  For master theise, it should be single-side printed when the total number of pages is below 100. How can I cancel these empty double pages in the end of chapter ?

**Comment by sighingnow** [comment] 2016-12-15 14:22
In line 2 of `sample-master.tex`, we have

~~~
\documentclass[master,openright,twoside,color]{buaathesis}
~~~

Modify the argument `twoside` to `oneside` then your document will be single-side printed.

**Comment by huxuan** [comment] 2016-12-16 02:36
Close this issue as the problem is already solved and it become somewhat off topic. Please consider creating a new one with clear title/content so that other guys with similar problem can reach the answer easily.

**Closed by huxuan** 2016-12-16 02:36 UTC

**Comment by ipez** [comment] 2016-12-16 06:30
Very good. Thank you.
